[package]
name = "relations"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", default-features = false }
bulletproofs = { path = "../bulletproofs" }
ark-ff = { version = "0.3.0", features = ["parallel", "asm"] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-serialize = { version = "0.3.0" } 
ark-std = { version = "0.3.0", features = [ "parallel" ] }
merlin = { version = "2", default-features = false }
rust-crypto = "^0.2"
ark-crypto-primitives = { version = "0.3.0" } 
digest = "0.9"
blake2 = "0.9"

[dev-dependencies]
criterion = "0.3"
pasta = { path = "../pasta" }

[[bench]]
name = "select_rerandomize"
harness = false

[profile.release]
lto = true